"""Ready-made product squad: Facilitator, Growth PM, Product PM, Marketing PM, HX
researcher, Product Owner, Designer, Social Media.

Consuming projects supply only a `KnowledgeBase` (ADR 0003); roles and
contracts are fixed.
"""

from pydantic_squads.product.contracts import (
    AgentName,
    Backlog,
    Brief,
    BriefDraft,
    BriefRecord,
    BriefRejection,
    ComponentProposal,
    ContentPack,
    ContentPiece,
    CycleHeader,
    CycleSnapshot,
    DesignerOutput,
    Divergence,
    Finding,
    FindingKind,
    FounderQuestion,
    GapGroup,
    HumanDecision,
    HXAnswer,
    KnowledgeGap,
    MarketingGuidance,
    Opinion,
    OpinionDraft,
    POOutput,
    Prototype,
    Screen,
    SendBack,
    Span,
    SpanStatus,
    Story,
    Synthesis,
    SynthesisDraft,
    Triage,
    design_coverage_errors,
    validate_brief,
)
from pydantic_squads.product.knowledge import (
    KnowledgeBase,
    MarkdownKnowledgeBase,
    Note,
    NoteExcerpt,
    SerializedKnowledgeBase,
    excerpt,
    format_note,
)
from pydantic_squads.product.roles import (
    DESIGNER,
    FACILITATOR,
    GROWTH_PM,
    HX,
    PM_MARKETING,
    PM_PRODUCT,
    PRODUCT_OWNER,
    SOCIAL_MEDIA,
)
from pydantic_squads.product.squad import (
    COMMITTEE_ROLES,
    PRODUCT_POLICIES,
    Language,
    build_product_squad,
    product_owner_has_one_door,
)

__all__ = [
    "COMMITTEE_ROLES",
    "DESIGNER",
    "FACILITATOR",
    "GROWTH_PM",
    "HX",
    "PM_MARKETING",
    "PM_PRODUCT",
    "PRODUCT_OWNER",
    "PRODUCT_POLICIES",
    "SOCIAL_MEDIA",
    "AgentName",
    "Backlog",
    "Brief",
    "BriefDraft",
    "BriefRecord",
    "BriefRejection",
    "ComponentProposal",
    "ContentPack",
    "ContentPiece",
    "CycleHeader",
    "CycleSnapshot",
    "DesignerOutput",
    "Divergence",
    "Finding",
    "FindingKind",
    "FounderQuestion",
    "GapGroup",
    "HXAnswer",
    "HumanDecision",
    "KnowledgeBase",
    "KnowledgeGap",
    "Language",
    "MarkdownKnowledgeBase",
    "MarketingGuidance",
    "Note",
    "NoteExcerpt",
    "Opinion",
    "OpinionDraft",
    "POOutput",
    "Prototype",
    "Screen",
    "SendBack",
    "SerializedKnowledgeBase",
    "Span",
    "SpanStatus",
    "Story",
    "Synthesis",
    "SynthesisDraft",
    "Triage",
    "build_product_squad",
    "design_coverage_errors",
    "excerpt",
    "format_note",
    "product_owner_has_one_door",
    "validate_brief",
]
